from django.db import models

# Create your models here.

class turfuser(models.Model):
    
    username=models.CharField(max_length=255,unique=True)
    password=models.CharField(max_length=255,unique=True)
    ucontact=models.CharField(max_length=255,unique=True)
    umail=models.CharField(max_length=255,unique=True)
    uaddress=models.CharField(max_length=255)
    
class booking(models.Model):
    
    turfuser = models.ForeignKey(turfuser,on_delete=models.CASCADE)
    bdate = models.DateField()
    btime = models.CharField(default="0",max_length=255)
    sport = models.CharField(max_length=255)
    amount = models.CharField(max_length=255)
    
class Cricket(models.Model):
    
    tdate = models.DateField()
    FIVEAM = models.CharField(default='green',max_length=255)
    SIXAM = models.CharField(default='green',max_length=255)
    SEVENAM = models.CharField(default='green',max_length=255)
    EIGHTAM = models.CharField(default='green',max_length=255)
    NINEAM = models.CharField(default='green',max_length=255)
    TENAM = models.CharField(default='green',max_length=255)
    ELEAM = models.CharField(default='green',max_length=255)
    TWEPM = models.CharField(default='green',max_length=255)
    ONEPM = models.CharField(default='green',max_length=255)
    TWOPM = models.CharField(default='green',max_length=255)
    THREEPM = models.CharField(default='green',max_length=255)
    FOURPM = models.CharField(default='green',max_length=255)
    FIVEPM = models.CharField(default='green',max_length=255)
    SIXPM = models.CharField(default='green',max_length=255)
    SEVENPM = models.CharField(default='green',max_length=255)
    EIGHTPM = models.CharField(default='green',max_length=255)
    NINEPM = models.CharField(default='green',max_length=255)
    TENPM = models.CharField(default='green',max_length=255)
    
class Cricket1(models.Model):
    
    tdate = models.DateField()
    FIVEAM = models.CharField(default='show',max_length=255)
    SIXAM = models.CharField(default='show',max_length=255)
    SEVENAM = models.CharField(default='show',max_length=255)
    EIGHTAM = models.CharField(default='show',max_length=255)
    NINEAM = models.CharField(default='show',max_length=255)
    TENAM = models.CharField(default='show',max_length=255)
    ELEAM = models.CharField(default='show',max_length=255)
    TWEPM = models.CharField(default='show',max_length=255)
    ONEPM = models.CharField(default='show',max_length=255)
    TWOPM = models.CharField(default='show',max_length=255)
    THREEPM = models.CharField(default='show',max_length=255)
    FOURPM = models.CharField(default='show',max_length=255)
    FIVEPM = models.CharField(default='show',max_length=255)
    SIXPM = models.CharField(default='show',max_length=255)
    SEVENPM = models.CharField(default='show',max_length=255)
    EIGHTPM = models.CharField(default='show',max_length=255)
    NINEPM = models.CharField(default='show',max_length=255)
    TENPM = models.CharField(default='show',max_length=255)
    
class football(models.Model):
    
    tdate = models.DateField()
    FIVEAM = models.CharField(default='green',max_length=255)
    SIXAM = models.CharField(default='green',max_length=255)
    SEVENAM = models.CharField(default='green',max_length=255)
    EIGHTAM = models.CharField(default='green',max_length=255)
    NINEAM = models.CharField(default='green',max_length=255)
    TENAM = models.CharField(default='green',max_length=255)
    ELEAM = models.CharField(default='green',max_length=255)
    TWEPM = models.CharField(default='green',max_length=255)
    ONEPM = models.CharField(default='green',max_length=255)
    TWOPM = models.CharField(default='green',max_length=255)
    THREEPM = models.CharField(default='green',max_length=255)
    FOURPM = models.CharField(default='green',max_length=255)
    FIVEPM = models.CharField(default='green',max_length=255)
    SIXPM = models.CharField(default='green',max_length=255)
    SEVENPM = models.CharField(default='green',max_length=255)
    EIGHTPM = models.CharField(default='green',max_length=255)
    NINEPM = models.CharField(default='green',max_length=255)
    TENPM = models.CharField(default='green',max_length=255)
    
class football1(models.Model):
    
    tdate = models.DateField()
    FIVEAM = models.CharField(default='show',max_length=255)
    SIXAM = models.CharField(default='show',max_length=255)
    SEVENAM = models.CharField(default='show',max_length=255)
    EIGHTAM = models.CharField(default='show',max_length=255)
    NINEAM = models.CharField(default='show',max_length=255)
    TENAM = models.CharField(default='show',max_length=255)
    ELEAM = models.CharField(default='show',max_length=255)
    TWEPM = models.CharField(default='show',max_length=255)
    ONEPM = models.CharField(default='show',max_length=255)
    TWOPM = models.CharField(default='show',max_length=255)
    THREEPM = models.CharField(default='show',max_length=255)
    FOURPM = models.CharField(default='show',max_length=255)
    FIVEPM = models.CharField(default='show',max_length=255)
    SIXPM = models.CharField(default='show',max_length=255)
    SEVENPM = models.CharField(default='show',max_length=255)
    EIGHTPM = models.CharField(default='show',max_length=255)
    NINEPM = models.CharField(default='show',max_length=255)
    TENPM = models.CharField(default='show',max_length=255)
    
class volleyball(models.Model):
    
    tdate = models.DateField()
    FIVEAM = models.CharField(default='green',max_length=255)
    SIXAM = models.CharField(default='green',max_length=255)
    SEVENAM = models.CharField(default='green',max_length=255)
    EIGHTAM = models.CharField(default='green',max_length=255)
    NINEAM = models.CharField(default='green',max_length=255)
    TENAM = models.CharField(default='green',max_length=255)
    ELEAM = models.CharField(default='green',max_length=255)
    TWEPM = models.CharField(default='green',max_length=255)
    ONEPM = models.CharField(default='green',max_length=255)
    TWOPM = models.CharField(default='green',max_length=255)
    THREEPM = models.CharField(default='green',max_length=255)
    FOURPM = models.CharField(default='green',max_length=255)
    FIVEPM = models.CharField(default='green',max_length=255)
    SIXPM = models.CharField(default='green',max_length=255)
    SEVENPM = models.CharField(default='green',max_length=255)
    EIGHTPM = models.CharField(default='green',max_length=255)
    NINEPM = models.CharField(default='green',max_length=255)
    TENPM = models.CharField(default='green',max_length=255)
    
class volleyball1(models.Model):
    
    tdate = models.DateField()
    FIVEAM = models.CharField(default='show',max_length=255)
    SIXAM = models.CharField(default='show',max_length=255)
    SEVENAM = models.CharField(default='show',max_length=255)
    EIGHTAM = models.CharField(default='show',max_length=255)
    NINEAM = models.CharField(default='show',max_length=255)
    TENAM = models.CharField(default='show',max_length=255)
    ELEAM = models.CharField(default='show',max_length=255)
    TWEPM = models.CharField(default='show',max_length=255)
    ONEPM = models.CharField(default='show',max_length=255)
    TWOPM = models.CharField(default='show',max_length=255)
    THREEPM = models.CharField(default='show',max_length=255)
    FOURPM = models.CharField(default='show',max_length=255)
    FIVEPM = models.CharField(default='show',max_length=255)
    SIXPM = models.CharField(default='show',max_length=255)
    SEVENPM = models.CharField(default='show',max_length=255)
    EIGHTPM = models.CharField(default='show',max_length=255)
    NINEPM = models.CharField(default='show',max_length=255)
    TENPM = models.CharField(default='show',max_length=255)
    
class basketball(models.Model):
    
    tdate = models.DateField()
    FIVEAM = models.CharField(default='green',max_length=255)
    SIXAM = models.CharField(default='green',max_length=255)
    SEVENAM = models.CharField(default='green',max_length=255)
    EIGHTAM = models.CharField(default='green',max_length=255)
    NINEAM = models.CharField(default='green',max_length=255)
    TENAM = models.CharField(default='green',max_length=255)
    ELEAM = models.CharField(default='green',max_length=255)
    TWEPM = models.CharField(default='green',max_length=255)
    ONEPM = models.CharField(default='green',max_length=255)
    TWOPM = models.CharField(default='green',max_length=255)
    THREEPM = models.CharField(default='green',max_length=255)
    FOURPM = models.CharField(default='green',max_length=255)
    FIVEPM = models.CharField(default='green',max_length=255)
    SIXPM = models.CharField(default='green',max_length=255)
    SEVENPM = models.CharField(default='green',max_length=255)
    EIGHTPM = models.CharField(default='green',max_length=255)
    NINEPM = models.CharField(default='green',max_length=255)
    TENPM = models.CharField(default='green',max_length=255)
    
class basketball1(models.Model):
    
    tdate = models.DateField()
    FIVEAM = models.CharField(default='show',max_length=255)
    SIXAM = models.CharField(default='show',max_length=255)
    SEVENAM = models.CharField(default='show',max_length=255)
    EIGHTAM = models.CharField(default='show',max_length=255)
    NINEAM = models.CharField(default='show',max_length=255)
    TENAM = models.CharField(default='show',max_length=255)
    ELEAM = models.CharField(default='show',max_length=255)
    TWEPM = models.CharField(default='show',max_length=255)
    ONEPM = models.CharField(default='show',max_length=255)
    TWOPM = models.CharField(default='show',max_length=255)
    THREEPM = models.CharField(default='show',max_length=255)
    FOURPM = models.CharField(default='show',max_length=255)
    FIVEPM = models.CharField(default='show',max_length=255)
    SIXPM = models.CharField(default='show',max_length=255)
    SEVENPM = models.CharField(default='show',max_length=255)
    EIGHTPM = models.CharField(default='show',max_length=255)
    NINEPM = models.CharField(default='show',max_length=255)
    TENPM = models.CharField(default='show',max_length=255)
    
    
class handball(models.Model):
    
    tdate = models.DateField()
    FIVEAM = models.CharField(default='green',max_length=255)
    SIXAM = models.CharField(default='green',max_length=255)
    SEVENAM = models.CharField(default='green',max_length=255)
    EIGHTAM = models.CharField(default='green',max_length=255)
    NINEAM = models.CharField(default='green',max_length=255)
    TENAM = models.CharField(default='green',max_length=255)
    ELEAM = models.CharField(default='green',max_length=255)
    TWEPM = models.CharField(default='green',max_length=255)
    ONEPM = models.CharField(default='green',max_length=255)
    TWOPM = models.CharField(default='green',max_length=255)
    THREEPM = models.CharField(default='green',max_length=255)
    FOURPM = models.CharField(default='green',max_length=255)
    FIVEPM = models.CharField(default='green',max_length=255)
    SIXPM = models.CharField(default='green',max_length=255)
    SEVENPM = models.CharField(default='green',max_length=255)
    EIGHTPM = models.CharField(default='green',max_length=255)
    NINEPM = models.CharField(default='green',max_length=255)
    TENPM = models.CharField(default='green',max_length=255)
    
class handball1(models.Model):
    
    tdate = models.DateField()
    FIVEAM = models.CharField(default='show',max_length=255)
    SIXAM = models.CharField(default='show',max_length=255)
    SEVENAM = models.CharField(default='show',max_length=255)
    EIGHTAM = models.CharField(default='show',max_length=255)
    NINEAM = models.CharField(default='show',max_length=255)
    TENAM = models.CharField(default='show',max_length=255)
    ELEAM = models.CharField(default='show',max_length=255)
    TWEPM = models.CharField(default='show',max_length=255)
    ONEPM = models.CharField(default='show',max_length=255)
    TWOPM = models.CharField(default='show',max_length=255)
    THREEPM = models.CharField(default='show',max_length=255)
    FOURPM = models.CharField(default='show',max_length=255)
    FIVEPM = models.CharField(default='show',max_length=255)
    SIXPM = models.CharField(default='show',max_length=255)
    SEVENPM = models.CharField(default='show',max_length=255)
    EIGHTPM = models.CharField(default='show',max_length=255)
    NINEPM = models.CharField(default='show',max_length=255)
    TENPM = models.CharField(default='show',max_length=255)
    
    
class kabaddi(models.Model):
    
    tdate = models.DateField()
    FIVEAM = models.CharField(default='green',max_length=255)
    SIXAM = models.CharField(default='green',max_length=255)
    SEVENAM = models.CharField(default='green',max_length=255)
    EIGHTAM = models.CharField(default='green',max_length=255)
    NINEAM = models.CharField(default='green',max_length=255)
    TENAM = models.CharField(default='green',max_length=255)
    ELEAM = models.CharField(default='green',max_length=255)
    TWEPM = models.CharField(default='green',max_length=255)
    ONEPM = models.CharField(default='green',max_length=255)
    TWOPM = models.CharField(default='green',max_length=255)
    THREEPM = models.CharField(default='green',max_length=255)
    FOURPM = models.CharField(default='green',max_length=255)
    FIVEPM = models.CharField(default='green',max_length=255)
    SIXPM = models.CharField(default='green',max_length=255)
    SEVENPM = models.CharField(default='green',max_length=255)
    EIGHTPM = models.CharField(default='green',max_length=255)
    NINEPM = models.CharField(default='green',max_length=255)
    TENPM = models.CharField(default='green',max_length=255)
    
class kabaddi1(models.Model):
    
    tdate = models.DateField()
    FIVEAM = models.CharField(default='show',max_length=255)
    SIXAM = models.CharField(default='show',max_length=255)
    SEVENAM = models.CharField(default='show',max_length=255)
    EIGHTAM = models.CharField(default='show',max_length=255)
    NINEAM = models.CharField(default='show',max_length=255)
    TENAM = models.CharField(default='show',max_length=255)
    ELEAM = models.CharField(default='show',max_length=255)
    TWEPM = models.CharField(default='show',max_length=255)
    ONEPM = models.CharField(default='show',max_length=255)
    TWOPM = models.CharField(default='show',max_length=255)
    THREEPM = models.CharField(default='show',max_length=255)
    FOURPM = models.CharField(default='show',max_length=255)
    FIVEPM = models.CharField(default='show',max_length=255)
    SIXPM = models.CharField(default='show',max_length=255)
    SEVENPM = models.CharField(default='show',max_length=255)
    EIGHTPM = models.CharField(default='show',max_length=255)
    NINEPM = models.CharField(default='show',max_length=255)
    TENPM = models.CharField(default='show',max_length=255)
    
