# Generated by Django 5.0.6 on 2024-09-19 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bdate', models.DateField()),
                ('btime', models.CharField(default='0', max_length=255)),
                ('sport', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('turfuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.turfuser')),
            ],
        ),
    ]
