# Generated by Django 5.0.6 on 2024-09-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turfuser',
            name='password',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='turfuser',
            name='ucontact',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='turfuser',
            name='umail',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='turfuser',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
